---
language: "python"
python:
- 2.7

env:
- ANSIBLE_VERSION=1.5
- ANSIBLE_VERSION=1.5.1
- ANSIBLE_VERSION=1.5.2
- ANSIBLE_VERSION=1.5.3
- ANSIBLE_VERSION=1.5.4
- ANSIBLE_VERSION=1.5.5
- ANSIBLE_VERSION=1.6
- ANSIBLE_VERSION=1.6.1
- ANSIBLE_VERSION=1.6.2
- ANSIBLE_VERSION=1.6.3
- ANSIBLE_VERSION=1.6.4
- ANSIBLE_VERSION=1.6.5
- ANSIBLE_VERSION=1.6.6
- ANSIBLE_VERSION=1.6.7
- ANSIBLE_VERSION=1.6.8
- ANSIBLE_VERSION=1.6.9
- ANSIBLE_VERSION=1.6.10
- ANSIBLE_VERSION=1.7
- ANSIBLE_VERSION=1.7.1
- ANSIBLE_VERSION=1.7.2
- ANSIBLE_VERSION=1.8
- ANSIBLE_VERSION=1.8.1
- ANSIBLE_VERSION=1.8.2
- ANSIBLE_VERSION=1.8.3
- ANSIBLE_VERSION=1.8.4
- ANSIBLE_VERSION=1.9.0.1
- ANSIBLE_VERSION=1.9.1
- ANSIBLE_VERSION=1.9.2
- ANSIBLE_VERSION=1.9.3
- ANSIBLE_VERSION=1.9.4

before_install:
# Make sure everything's up to date.
- sudo apt-get update -qq

# Remove MySQL
- sudo apt-get remove --purge 'mysql*'
- sudo apt-get autoremove
- sudo apt-get autoclean
- sudo rm -rf /var/lib/mysql
- sudo truncate -s 0 /var/log/mysql/error.log

install:
- pip install ansible==$ANSIBLE_VERSION
- "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
- "ansible-playbook -i tests/travis-inventory tests/travis-playbook.yml --syntax-check"
- "ansible-playbook -i tests/travis-inventory tests/travis-playbook.yml --connection=local --sudo"
- >
  ansible-playbook -i tests/travis-inventory tests/travis-playbook.yml --connection=local --sudo
  | grep -q 'changed=0.*failed=0'
  && (echo 'Idempotence test: pass' && exit 0)
  || (echo 'Idempotence test: fail' && exit 1)
- >
  echo "STATUS;" | sudo mysql --batch
  | grep -q 'mysql'
  && (echo 'MySQL Connection via socket successful' && exit 0)
  || (echo 'MySQL Connection via socket failed'     && exit 1)
