---

- name: install mysql-server
  apt:
    name: '{{ mysql_package_list }}'

- name: Check if installing for the first time
  stat:
    path: /root/.my.cnf
  register: my_cnf

- name: Ensure mysql server is running
  service:
    name: mysql
    state: started  
  when: not my_cnf.stat.exists

- name: set mysql root password
  shell: 
    cmd: "mysqladmin -u root password {{ mysql_root_password }}"
  when: not my_cnf.stat.exists
  no_log: true

- name: create mysql password file
  template:
    src: templates/my.cnf
    dest: /root/.my.cnf
  when: not my_cnf.stat.exists
  no_log: true

- name: configure mysql tunables
  lineinfile:
    dest: '/etc/mysql/my.cnf'
    regexp: '^{{item.key}}(\s+)?=\s?(.+)?'
    line: '{{item.key}} = {{item.value}}'
    insertafter: '\[mysqld\]'
  with_dict: '{{mysqld_tunables|default({})}}'
  notify: restart mysql
